version: '3.1'

services:
  main:
    image: jenkins-pipeline:latest
    environment:
      - JENKINS_UI_URL=${JENKINS_URL}
    ports:
      - 8081:8080
      - 50000:50000
    secrets:
      - admin-username
      - admin-password
      - aws-codecommit-master-user
      - aws-codecommit-master-pwd

secrets:
  admin-username:
    external: true
  admin-password:
    external: true
  aws-codecommit-master-user:
    external: true
  aws-codecommit-master-pwd:
    external: true
