version: '3.1'

services:
  main:
    image: bbideep/jenkins:1.0
    environment:
      - JENKINS_UI_URL=${JENKINS_URL}
    ports:
      - 8081:8080
      - 50000:50000
    secrets:
      - admin-username
      - admin-password

secrets:
  admin-username:
    external: true
  admin-password:
    external: true
