version: '3.1'

services:
  main:
    image: jenkins-pipeline:latest
    environment:
      - JENKINS_UI_URL=${JENKINS_URL}
      - GIT_REPO_HTTPS_URL=${GIT_REPO_HTTPS_URL:-https://git-codecommit.us-east-1.amazonaws.com/v1/repos/jenkins-pipeline}
      - GIT_BRANCH=${GIT_BRANCH:-master}
    ports:
      - 8081:8080
      - 50000:50000
    secrets:
      - admin-username
      - admin-password
      - scm-repo-user
      - scm-repo-pwd

secrets:
  admin-username:
    external: true
  admin-password:
    external: true
  scm-repo-user:
    external: true
  scm-repo-pwd:
    external: true
