version: '3.1'

services:
  main:
    image: jenkins-pipeline:latest
    environment:
      - JENKINS_UI_URL=${JENKINS_URL}
      - GIT_REPO_HTTPS_URL=${GIT_REPO_HTTPS_URL}
      - GIT_BRANCH=${GIT_BRANCH}
    ports:
      - 8081:8080
      - 50000:50000
    secrets:
      - admin-username
      - admin-password

secrets:
  admin-username:
    external: true
  admin-password:
    external: true
